# # # name: First Workflow

# # # on:
# # #   push:
# # #     branches:
# # #       - master

# # # jobs:
# # #   test-job:
# # #     runs-on: ubuntu-latest

# # #     steps:
# # #       - name: Print message
# # #         run: echo "GitHub Actions is working!"

# # #   second-job:
# # #     runs-on: ubuntu-latest

# # #     steps:
# # #       - name: Say Hello
# # #         run: echo "Hello!"

# # #       - name: Show Date
# # #         run: date

# # #   third-job:
# # #     runs-on: ubuntu-latest

# # #     steps:
# # #       - name: List Files
# # #         run: ls -la
# # name: Uses action

# # on:
# #   push:
# #   pull_request:
# #     branches:
# #       - main

# # jobs:
# #   test:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v4

# #       - name: Setup Node
# #         uses: actions/setup-node@v4
# #         with:
# #           node-version: 18

# #       - name: Check Node version
# #         run: node -v

# #       - name: List files
# #         run: ls
#         name : Uses Action
# on : push
# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name : Checkout code // clone a repo
#         uses : actions/checkout@v4
      
#       - name : setup node
#         uses : actions/setup-node@v4

#       - name : Download dependency
#         run : npm i 

#       - name : Run tests
#         run : npm run test

#       - name : list file
#         run : ls
name: Uses action
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  jobs1:
     runs-on: ubuntu-latest
     steps:
     - name:create a file
        run: echo "Hello World" > file.txt
     - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-file
          path:file.txt
  jobs2:
     runs-on: ubuntu-latest
     needs: jobs1
     steps:
     - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-file
      - name: read file
        run: cat file.txt